### ISSUE TITLE
pyscenic does not contain genesig

### ISSUE THREAD

**Issue by rekado** [BIMSBbioinfo/ikarus#12]
The latest release of pySCENIC no longer provides pyscenic.genesig:

https://github.com/aertslab/pySCENIC/commit/a137cd16bbbb327d56d2a4e9d454c7b316199437

This has moved to ctxcore.

**Comment by erevkov** [comment]
Hi! I wanted to try using the package, but after installing I ran into the same error: `ModuleNotFoundError: No module named 'pyscenic.genesig'` (Python 3.8, installed with pip+git in a conda environment). Will there be a fix anytime soon, or perhaps there is a fixed version available elsewhere already?

**Comment by rekado** [comment]
@erevkov in the meantime you can patch this by replacing "pyscenic.genesig" with "ctxcore.genesig" in ikarus/classifier.py.

**Comment by dohmjan** [comment]
Hi! Thank you for the hint, it's now also changed in the repo.

**Comment by melonheader** [comment]
@erevkov Could you tell if the model works for you after the update?

**Comment by erevkov** [comment]
Yep, looks like this is working now, thanks!
