### ISSUE TITLE
glmer model failed to converge

### ISSUE THREAD

**Issue by Fas9ly** [BIMSBbioinfo/ikarus#20]
Hi everyone,
As with almost everyone, I have run into this warning "model failed to converge" and I need help to clear this warning message while running my glmer analysis. 
" Warning message:
In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model failed to converge with max|grad| = 0.00272495 (tol = 0.002, component 1)" 

I managed to clear it before by changing the optimizer in the first two models I am running but I have tried all the optimizers so far and nothing seem to be working. 
glmer code:
 model_300 <- glmer(correlation_effect ~language + proficiency.level + verb.freq + language:proficiency.level+ language:verb.freq+ proficiency.level:verb.freq + (1 | ID) + (1 | test.verb), 
                   data =accuracy.data,family = binomial(link = "logit"),control = glmerControl(optimizer = "nloptwrap",  optCtrl = list(algorithm= "NLOPT_LN_NELDERMEAD")))
  
![SCR-20230927-nv4](https://github.com/BIMSBbioinfo/ikarus/assets/146216420/48f10c06-f76c-4437-9f72-5fe944e2f39d)

Model summary:

![SCR-20230927-ngf](https://github.com/BIMSBbioinfo/ikarus/assets/146216420/254bf389-3c0a-4e23-ae75-72cd28800c5c)

allFit summary:
![SCR-20230927-ntu](https://github.com/BIMSBbioinfo/ikarus/assets/146216420/7798d0b2-fd19-4e5c-8efc-de2cf55a2b21)

Trying different optimizers using the following functions:
 
![SCR-20230927-nrz](https://github.com/BIMSBbioinfo/ikarus/assets/146216420/8cfb9b24-d6e5-4818-b6b0-4ae048f5c5ba)

What else I could do to solve this issue? 
Thanks in advance ;)

**Comment by melonheader** [comment]
Hello @Fas9ly,

I would be glad to be of help, but it seems to me that you referring to another package, which might be of a similar name but surely serves a different purpose :^)
