### ISSUE TITLE
ContextualVersionConflict

### ISSUE THREAD

**Issue by skr3178** [BIMSBbioinfo/ikarus#7]
`!python -m pip install git+https://github.com/BIMSBbioinfo/ikarus.git
from ikarus import classifier, utils, data`

ContextualVersionConflict: (pyarrow 6.0.1 (/usr/local/lib/python3.7/dist-packages), Requirement.parse('pyarrow<0.17.0,>=0.11.1'), {'ctxcore'})

**Comment by dohmjan** [comment]
Hi! 
Thank you for pointing that out.
Were your trying to install ikarus from within google colab? The ContextualVersionConflict seems related. 
As described [here](https://stackoverflow.com/questions/58201636/contextual-version-conflict-error-google-colab) you would have to install pyarrow in the correct version manually -- you already suggested that (#8, thank you!).

Outside colab, pip should take care of the pyarrow version as defined in [ctxcore](https://github.com/aertslab/ctxcore/blob/main/requirements.txt) as long as one is using python<=3.8.

**Comment by dohmjan** [comment]
Due to an update in ctxcore this should be resolved in general. I'll close the issue for now. Can be opened again, if there are any questions.
