### ISSUE TITLE
Key error- related to joblib version?

### ISSUE THREAD

**Issue by JahanRahman** [BIMSBbioinfo/ikarus#9]
code:
import urllib.request
import anndata
import pandas as pd
from pathlib import Path
from ikarus import classifier, utils, data

signatures_path = Path("signatures.gmt")

model = classifier.Ikarus(signatures_gmt = signatures_path, out_dir = "ikarus_model")

core_model_path = Path("core_model.joblib")

model.load_core_model(core_model_path)

error:
  File "ikarus_cell_classifier.py", line 13, in <module>
    model.load_core_model(core_model_path)
  File "/work/rux/lib/python3.8/site-packages/ikarus/classifier.py", line 486, in load_core_model
    self.core_model = joblib.load(core_model_path)
  File "/work/rux/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 587, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/work/rux/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 506, in _unpickle
    obj = unpickler.load()
  File "/work/lib/python3.8/pickle.py", line 1210, in load
    dispatch[key[0]](self)
KeyError: 10

I get the same error with version 3.8.0 and 3.8.5 python. I suspect it has something to do with a discrepancy in joblib versions?

**Comment by dohmjan** [comment]
Hi Jahan,

Thank you for pointing out the issue. I am trying to reproduce it. As you said, it might be due to a version discrepancy. Could you tell me your version numbers for joblib, numpy, scikit-learn and maybe scipy?

Jan

**Comment by dohmjan** [comment]
Numpy 1.23.0 seems to be quite new. At least I can't install it successfully together with ikarus. Could you maybe try Numpy 1.22.4? Other than that, the versions seem to be fine. (You will probably get a warning when loading the model, as it was created with sklearn==0.24.2 - but should be ok anyway.)
Did you install ikarus via `pip install ikarus` ?

**Comment by JahanRahman** [comment]
Hi Jan,  

So I created a python venv using python 3.8.5.  The I  tried pip installing numpy==1.22.4 and it installed successfully, but I got the following error message:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyega3 4.0.0 requires psutil==5.6.6, but you have psutil 5.9.0 which is incompatible.
pyega3 4.0.0 requires requests==2.26.0, but you have requests 2.27.1 which is incompatible.
pyega3 4.0.0 requires tqdm==4.19.6, but you have tqdm 4.63.0 which is incompatible.
pyega3 4.0.0 requires urllib3==1.26.7, but you have urllib3 1.26.8 which is incompatible.

So for good measure I pip installed each of those specific versions of those packages.  
 Then I pip installed ikarus with no issue.  Yet when trying to load the core_model  I'm still getting the same key error. I tried installing sklearn==0.24.2 after this but it seems like that version is no longer available.  Any additional suggestions?

**Comment by dohmjan** [comment]
Hmm, actually, ikarus should not be related to pyega3. 
For testing purpose could you maybe create a new python venv or conda env and try just installing ikarus via pip, something like:
```
virtualenv ./ikarus-venv --python=python3.8
source ./ikarus-venv/bin/activate
pip install ikarus
```

or 

```
conda create --name ikarus-conda python=3.8
conda activate ikarus-conda
pip install ikarus
```

**Comment by JahanRahman** [comment]
I just tried the latter option and upon trying to install ikarus and everything installed correctly without error. Yet I still get the key error.  I also double checked version numbers of the relevant packages again, and they all seem to be correct:
joblib - '1.1.0'
numpy - '1.22.4'
sklearn - '1.1.1'
scipy - '1.8.1'

**Comment by dohmjan** [comment]
Given that, I am afraid, currently I can't come up with an obvious reason for why you can't load the pretrained model. Instead, is it maybe somehow possible for you to create the model yourself following the [tutorial](https://github.com/BIMSBbioinfo/ikarus/blob/master/tutorials/tutorial.ipynb)? This should end up and store the same model.

**Comment by JahanRahman** [comment]
Hi Jan creating the model myself worked! Thanks so much for the help!
